### ISSUE TITLE
Releases tab is empty(at least for me)

### ISSUE THREAD

**Issue by BoykoDenis** [3011t/ma2-poznamky#11]
I dont see any release files on github so there is no way to build the pdf file. What is the solution for that?

**Comment by TennesseeTrash** [comment]
Hi,
there are no releases in this repo. If you want to build the notes, just clone the edit branch and build the notes from that. Alternatively, you can download a prebuilt PDF from [Tom Sláma's website](https://slama.dev/poznamky-z-prednasky/matematicka-analyza-ii/) (I think he has an up-to-date version there).
